# Generated by Django 4.1.6 on 2023-02-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gmt_offset', models.IntegerField()),
                ('created_time', models.DateTimeField()),
            ],
        ),
    ]
