# Generated by Django 4.2.1 on 2023-05-13 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeshift', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('name',), 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
    ]
